spring.application.name=InterviewMate

# PostgreSQL (production / development) - main DB
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# CORRECT HIBERNATE DIALECT FOR POSTGRESQL
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT defaults (override in prod)
app.jwt.secret=${JWT_SECRET}
app.jwt.expiration-ms=3600000
